import Image from 'next/image'
import { Inter } from 'next/font/google'
import Head from 'next/head'
import { Header } from '@/components/Header'
import { Hero } from '@/components/Hero'
import { SectionTools } from '@/components/SectionTools'
import { SectionPrivateFest } from '@/components/SectionPrivateFest'
import { Footer } from '@/components/Footer'
import { SectionEventBar } from '@/components/SectionEventBar'
import { SectionPartner } from '@/components/SectionPartner'
import { SectionQuest } from '@/components/SectionQuest'
import { SectionQuestFest } from '@/components/SectionQuestFest'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Ventus | Crie eventos para todas ocasiões</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="theme-color" content="#000" />
        <meta property="og:image" content="/img-ventus-banner.png" />

      </Head>

      <style>{`
        ::-webkit-scrollbar {
          width: 0.5vw;
          background: black;
          padding-right: 3px;
        }

        ::-webkit-scrollbar-thumb {
          background: #DB3535;
          border-radius: 50px;
        }
      `}
      </style>

      <div className="h-full relative z-40  bg-black">
        <header id="header" className="container:px-4 bg-ventus-primary">
          <Header />
        </header>

        <main className="h-full bg-ventus-primary overflow-x-hidden">
          <section className="container:px-4 bg-ventus-primary ">
            <div className="w-[376px] h-[375px] absolute left-[-182px] top-[436px] bg-red-600 rounded-full blur-[200px]" />
           
            <Hero />
          </section>

          <section id="tools" className="container:px-4 bg-ventus-primary relative z-10">
            <div className="w-[317px] h-[317px] absolute left-[-150px] bottom-[296px] bg-red-600 rounded-full blur-[200px]" />
            <SectionTools />
            <div className="w-[445px] h-[445px] absolute right-[315px] bottom-[268px] bg-red-600 rounded-full blur-[305px]" />
          </section>

          <section id="private-fest" className="container:px-4 bg-ventus-primary relative z-10">
            <SectionPrivateFest />
          </section>

          <section id="quest-fest" className="container:px-4 bg-ventus-primary relative z-10">
            <SectionQuestFest />
            <div className="w-[298px] h-[230px] absolute right-[532px] top-[277px] bg-red-600 rounded-full blur-[254px]" />
          </section>

          <section id="tools-bar" className="container:px-4 bg-ventus-primary relative z-10">
            <SectionEventBar />
          </section>

          <section id="partner" className="container:px-4 bg-ventus-primary relative z-10">
            <div className="w-[298px] h-[230px]  absolute left-[180px] top-[-22px] bg-purple-500 rounded-full blur-[254px]" />
            <SectionPartner />
            <div className="w-[419px] h-[323px]  absolute right-[31px] bottom-[89px] bg-purple-500 rounded-full blur-[254px]" />
          </section>

          <section id="quest" className="container:px-4 bg-ventus-primary relative z-10">
            <SectionQuest />
          </section>
        </main>
        <div>
          <footer id="contact" className="container:px-4 bg-ventus-primary">
            <Footer />
          </footer>
        </div>
      </div>
    </>
  )
}
